### ISSUE TITLE
Feature request: different shortcuts for different search engines

### ISSUE THREAD

**Issue by thomarse-ef** [xelad0m/just-another-search-bar#1]
Thanks for this excellent extension. I'd like to make a feature request: it would be really handy if there was a quick way to change the search engine, without having to open the settings. Having different keyboard shortcuts associated with each installed search engine would be ideal, but even just a drop-down menu from the search bar would work. I'd also like to request that DuckDuckGo should be installed by default!

**Comment by xelad0m** [comment]
Thanks for the recommendations. I will try to add a feature with a search selection not through the settings soon. The rest of the thoughts are also interesting, I'll think about it.

**Comment by xelad0m** [comment]
After thinking about it, I realized that it would not be possible to implement such options in some simple way, without a global rewriting of the extension. As for search engines, they are given only as an example, you can always click the "minus" button in the settings and delete any of them. Adding a search command is also not difficult: 
press + in settings and enter something like this:

- `duckduckgo`
- `xdg-open https://duckduckgo.com/?q=#`
- `#`
- `+`
