### ISSUE TITLE
unable to change the keyboard shortcut

### ISSUE THREAD

**Issue by jothi-prasath** [xelad0m/just-another-search-bar#3]
Archlinux gnome44.1

unable to change the keyboard shortcut

**Comment by xelad0m** [comment]
you can try to read current keyboard shortcut in your terminal with command

`dconf read /org/gnome/shell/extensions/just-another-search-bar/open-search-bar-key`

and you can set new keyboard shortcut in your terminal with command for example

`dconf write /org/gnome/shell/extensions/just-another-search-bar/open-search-bar-key "['<Control><Alt>f']"`

try to play with these commands, everything should work out

**Comment by jothi-prasath** [comment]
it works! thanks❤️
